import type { ResourceItem } from '@/types';
import {
  Cloud, Briefcase, Users, FileCode, Palette, Settings2, SearchCode,
  Image as ImageIcon, Paintbrush, Server, BookOpen, Bot, Layout, Zap, FileJson, Rss, Github, GitMerge, LifeBuoy, Code, MonitorPlay, Gamepad2, PencilRuler, Wand2, Regex, Package, Waves, Wind, Figma, Framer, Sparkles, TestTube2, ShieldCheck
} from 'lucide-react';

export const RESOURCES_DATA: ResourceItem[] = [
  // Hosting / CI-CD
  {
    id: "vercel",
    name: "Vercel",
    description: "Plataforma de hosting optimizada para Next.js y frontend moderno. CI/CD integrado.",
    url: "https://vercel.com",
    category: "hosting-ci-cd",
    tags: ["hosting", "nextjs", "frontend", "ci/cd", "serverless", "deployment"],
    icon: Zap,
  },
  {
    id: "render-hosting",
    name: "Render",
    description: "Plataforma unificada en la nube para construir y ejecutar todas tus apps y sitios web.",
    url: "https://render.com",
    category: "hosting-ci-cd",
    tags: ["hosting", "backend", "database", "cronjobs", "ci/cd", "paas"],
    icon: Server,
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Alternativa de código abierto a Firebase. Base de datos Postgres, Auth, Storage, y más.",
    url: "https://supabase.io",
    category: "hosting-ci-cd",
    tags: ["database", "auth", "storage", "realtime", "postgres", "backend"],
    icon: Users,
  },
  {
    id: "railway",
    name: "Railway",
    description: "Despliega aplicaciones sin preocuparte por la infraestructura. Conecta tu repo y listo.",
    url: "https://railway.app",
    category: "hosting-ci-cd",
    tags: ["hosting", "paas", "deployment", "backend", "database"],
    icon: GitMerge,
  },
  {
    id: "github-pages",
    name: "GitHub Pages",
    description: "Hospeda sitios web estáticos directamente desde tu repositorio de GitHub.",
    url: "https://pages.github.com/",
    category: "hosting-ci-cd",
    tags: ["hosting", "static sites", "free", "github"],
    icon: Github,
  },
  {
    id: "netlify",
    name: "Netlify",
    description: "Plataforma para construir, desplegar y escalar aplicaciones web modernas.",
    url: "https://www.netlify.com/",
    category: "hosting-ci-cd",
    tags: ["hosting", "jamstack", "serverless functions", "ci/cd", "frontend"],
    icon: Cloud,
  },

  // Capacitación técnica / Onboarding
  {
    id: "freecodecamp",
    name: "freeCodeCamp",
    description: "Aprende a programar gratis. Construye proyectos. Obtén certificaciones.",
    url: "https://www.freecodecamp.org",
    category: "technical-training",
    tags: ["learn to code", "html", "css", "javascript", "react", "backend", "algorithms"],
    icon: BookOpen,
  },
  {
    id: "odin-project",
    name: "The Odin Project",
    description: "Currículum completo y gratuito para convertirte en desarrollador web full-stack.",
    url: "https://www.theodinproject.com",
    category: "technical-training",
    tags: ["full-stack", "html", "css", "javascript", "ruby", "rails", "nodejs"],
    icon: LifeBuoy,
  },
  {
    id: "scrimba",
    name: "Scrimba",
    description: "Plataforma interactiva para aprender a programar con cursos prácticos.",
    url: "https://scrimba.com",
    category: "technical-training",
    tags: ["interactive learning", "frontend", "react", "javascript", "python"],
    icon: MonitorPlay,
  },
  {
    id: "css-battle",
    name: "CSSBattle",
    description: "Juego para poner a prueba y mejorar tus habilidades de CSS replicando diseños.",
    url: "https://cssbattle.dev/",
    category: "technical-training",
    tags: ["css", "gamification", "challenge", "frontend"],
    icon: Gamepad2,
  },
  {
    id: "frontend-mentor",
    name: "Frontend Mentor",
    description: "Resuelve desafíos de frontend del mundo real. Mejora tus habilidades construyendo proyectos.",
    url: "https://www.frontendmentor.io/",
    category: "technical-training",
    tags: ["frontend", "html", "css", "javascript", "react", "vue", "angular", "projects"],
    icon: PencilRuler,
  },
  {
    id: "mdn-web-docs",
    name: "MDN Web Docs",
    description: "Documentación de referencia para tecnologías web abiertas, incluyendo HTML, CSS, y APIs JavaScript.",
    url: "https://developer.mozilla.org/",
    category: "technical-training",
    tags: ["documentation", "html", "css", "javascript", "web apis", "reference"],
    icon: Rss, // O BookOpen si ya no se usó
  },


  // Componentes de UI / Diseño
  {
    id: "shadcn-ui",
    name: "shadcn/ui",
    description: "Componentes de UI bellamente diseñados que puedes copiar y pegar en tus apps.",
    url: "https://ui.shadcn.com/",
    category: "ui-components-design",
    tags: ["react", "tailwind css", "components", "ui kit", "design system", "accessibility"],
    icon: Layout,
  },
  {
    id: "flowbite",
    name: "Flowbite",
    description: "Componentes de UI de código abierto construidos con Tailwind CSS.",
    url: "https://flowbite.com/",
    category: "ui-components-design",
    tags: ["tailwind css", "components", "ui kit", "figma"],
    icon: Figma,
  },
  {
    id: "tailwind-elements",
    name: "Tailwind Elements",
    description: "Componentes UI gratuitos para Tailwind CSS con funcionalidades interactivas.",
    url: "https://tailwind-elements.com/",
    category: "ui-components-design",
    tags: ["tailwind css", "components", "javascript"],
  },
  {
    id: "heroicons",
    name: "Heroicons",
    description: "Colección de íconos SVG de alta calidad hechos por los creadores de Tailwind CSS.",
    url: "https://heroicons.com/",
    category: "ui-components-design",
    tags: ["icons", "svg", "tailwind css"],
  },
  {
    id: "boxicons",
    name: "Boxicons",
    description: "Colección simple de íconos de código abierto cuidadosamente diseñados.",
    url: "https://boxicons.com/",
    category: "ui-components-design",
    tags: ["icons", "svg", "font icons"],
  },
  {
    id: "lucide-icons",
    name: "Lucide Icons",
    description: "Colección de íconos SVG simplemente hermosos y consistentes. Usados en este proyecto.",
    url: "https://lucide.dev/",
    category: "ui-components-design",
    tags: ["icons", "svg", "open source"],
    icon: Sparkles,
  },

  // Documentación técnica y PDF
  {
    id: "html2pdf-js",
    name: "html2pdf.js",
    description: "Generador de PDF del lado del cliente desde HTML. Ideal para facturas, reportes.",
    url: "https://ekoopmans.github.io/html2pdf.js/",
    category: "documentation-pdf",
    tags: ["pdf", "javascript", "html", "client-side"],
    icon: FileCode,
  },
  {
    id: "markdown-to-pdf",
    name: "Markdown to PDF (VS Code)",
    description: "Extensión de VS Code para exportar archivos Markdown a PDF.",
    url: "https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf",
    category: "documentation-pdf",
    tags: ["pdf", "markdown", "vscode", "documentation"],
  },
  {
    id: "jspdf",
    name: "jsPDF",
    description: "Librería para generar PDFs en JavaScript del lado del cliente.",
    url: "http://raw.githack.com/MrRio/jsPDF/master/docs/",
    category: "documentation-pdf",
    tags: ["pdf", "javascript", "client-side", "generator"],
  },

  // Online Tools
  {
    id: "caniuse",
    name: "Can I use",
    description: "Tablas de compatibilidad para tecnologías web frontend (HTML, CSS, JS).",
    url: "https://caniuse.com/",
    category: "online-tools",
    tags: ["compatibility", "html", "css", "javascript", "browsers", "frontend"],
    icon: SearchCode,
  },
  {
    id: "json-formatter-validator",
    name: "JSON Formatter & Validator",
    description: "Herramienta online para formatear y validar datos JSON.",
    url: "https://jsonformatter.curiousconcept.com/",
    category: "online-tools",
    tags: ["json", "formatter", "validator", "developer tools"],
    icon: FileJson,
  },
  {
    id: "regex101",
    name: "Regex101",
    description: "Debugger y probador de expresiones regulares online con resaltado de sintaxis.",
    url: "https://regex101.com/",
    category: "online-tools",
    tags: ["regex", "regular expressions", "developer tools", "tester"],
    icon: Regex,
  },
  {
    id: "bundlephobia",
    name: "BundlePhobia",
    description: "Analiza el tamaño de los paquetes npm y su impacto en el rendimiento.",
    url: "https://bundlephobia.com/",
    category: "online-tools",
    tags: ["npm", "package size", "performance", "javascript"],
    icon: Package,
  },
  {
    id: "readme-so",
    name: "readme.so",
    description: "Editor online para ayudarte a crear READMEs profesionales fácilmente.",
    url: "https://readme.so/",
    category: "online-tools",
    tags: ["readme", "markdown", "documentation", "github"],
  },


  // CSS Templates & Generators
  {
    id: "css-tricks-generators",
    name: "CSS-Tricks Generators",
    description: "Colección de generadores CSS útiles de CSS-Tricks (gradientes, selectores, etc.).",
    url: "https://css-tricks.com/tools/",
    category: "css-templates-generators",
    tags: ["css", "generators", "tools", "frontend", "snippets"],
    icon: Wand2,
  },
  {
    id: "neumorphism-io",
    name: "Neumorphism.io",
    description: "Generador de CSS para estilos de diseño Neumórfico.",
    url: "https://neumorphism.io/",
    category: "css-templates-generators",
    tags: ["css", "neumorphism", "ui design", "generator"],
  },
  {
    id: "getwaves",
    name: "Get Waves",
    description: "Generador de ondas SVG para usar en tus diseños web.",
    url: "https://getwaves.io/",
    category: "css-templates-generators",
    tags: ["svg", "waves", "design tool", "css background"],
    icon: Waves,
  },
  {
    id: "animista",
    name: "Animista",
    description: "Generador de animaciones CSS en línea con una variedad de presets.",
    url: "https://animista.net/",
    category: "css-templates-generators",
    tags: ["css", "animations", "generator", "frontend"],
    icon: Wind,
  },

  // Browser Extensions
  {
    id: "react-developer-tools",
    name: "React Developer Tools",
    description: "Extensión de navegador para depurar aplicaciones React.",
    url: "https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi",
    category: "browser-extensions",
    tags: ["react", "debugging", "devtools", "chrome", "firefox"],
    icon: Bot,
  },
  {
    id: "visbug",
    name: "VisBug",
    description: "Extensión de Chrome para editar visualmente el diseño de cualquier página web.",
    url: "https://chrome.google.com/webstore/detail/visbug/cdockenadnadldjbbgcallicgledbeoc",
    category: "browser-extensions",
    tags: ["css", "design", "developer tools", "chrome"],
  },
  {
    id: "colorzilla",
    name: "ColorZilla",
    description: "Selector de color avanzado, gotero, generador de gradientes y más.",
    url: "https://www.colorzilla.com/chrome/",
    category: "browser-extensions",
    tags: ["color picker", "css", "design tool", "chrome", "firefox"],
  },
  {
    id: "wappalyzer",
    name: "Wappalyzer",
    description: "Identifica las tecnologías utilizadas en los sitios web.",
    url: "https://www.wappalyzer.com/",
    category: "browser-extensions",
    tags: ["tech stack", "developer tools", "analysis"],
  },
  {
    id: "jsonview",
    name: "JSONView (Chrome/Firefox)",
    description: "Valida y visualiza documentos JSON directamente en el navegador.",
    url: "https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc",
    category: "browser-extensions",
    tags: ["json", "viewer", "developer tools", "chrome", "firefox"],
  },


  // Imágenes / Videos / Ilustraciones
  {
    id: "undraw",
    name: "unDraw",
    description: "Ilustraciones de código abierto para cualquier idea que puedas imaginar y crear.",
    url: "https://undraw.co/illustrations",
    category: "images-videos-illustrations",
    tags: ["illustrations", "svg", "open source", "design"],
    icon: ImageIcon,
  },
  {
    id: "pexels",
    name: "Pexels",
    description: "Fotos y videos de stock gratuitos que puedes usar en todas partes.",
    url: "https://www.pexels.com/",
    category: "images-videos-illustrations",
    tags: ["photos", "videos", "stock", "free"],
  },
  {
    id: "icons8-illustrations",
    name: "Icons8 Illustrations",
    description: "Ilustraciones de diseño gratuitas para potenciar tus proyectos.",
    url: "https://icons8.com/illustrations",
    category: "images-videos-illustrations",
    tags: ["illustrations", "design", "vectors", "free"],
  },
  {
    id: "unsplash",
    name: "Unsplash",
    description: "Fotos de alta resolución gratuitas, aportadas por una comunidad de fotógrafos.",
    url: "https://unsplash.com/",
    category: "images-videos-illustrations",
    tags: ["photos", "stock", "free", "high resolution"],
  },
  {
    id: "coverr",
    name: "Coverr",
    description: "Videos de stock hermosos y gratuitos para tu sitio web.",
    url: "https://coverr.co/",
    category: "images-videos-illustrations",
    tags: ["videos", "stock", "free", "background video"],
  },

  // Color, Tipografía e Inspiración Visual
  {
    id: "colorhunt",
    name: "ColorHunt",
    description: "Paletas de colores seleccionadas para diseñadores y artistas.",
    url: "https://colorhunt.co/",
    category: "color-typography-inspiration",
    tags: ["color", "palettes", "design", "inspiration"],
    icon: Paintbrush,
  },
  {
    id: "coolors",
    name: "Coolors",
    description: "Generador rápido de esquemas de color. Crea, guarda y comparte paletas.",
    url: "https://coolors.co/",
    category: "color-typography-inspiration",
    tags: ["color", "palettes", "generator", "design tool"],
  },
  {
    id: "google-fonts",
    name: "Google Fonts",
    description: "Amplia biblioteca de fuentes web de código abierto y gratuitas.",
    url: "https://fonts.google.com/",
    category: "color-typography-inspiration",
    tags: ["fonts", "typography", "web fonts", "free"],
  },
  {
    id: "dribbble",
    name: "Dribbble",
    description: "Comunidad para diseñadores donde mostrar su trabajo, obtener inspiración y feedback.",
    url: "https://dribbble.com/",
    category: "color-typography-inspiration",
    tags: ["design", "inspiration", "ui", "ux", "portfolio"],
    icon: Framer, // Opcional, Dribbble usa una 'd' minúscula
  },
  {
    id: "typewolf",
    name: "Typewolf",
    description: "Recurso independiente que muestra la tipografía en uso en la web.",
    url: "https://www.typewolf.com/",
    category: "color-typography-inspiration",
    tags: ["typography", "fonts", "inspiration", "design trends"],
  },
];
